### ISSUE TITLE
"Person" contact flaky

### ISSUE THREAD

**Issue by wongchristopher** [hjdhjd/homebridge-unifi-protect#683] opened 2022-02-23 23:35 UTC
**Describe The Problem:**

After the HKSV update the "Person" contact sensor has become inconsistent.  This actually worked perfectly before I switched over to HKSV.  It will trigger fine sometimes, but other times it will randomly stop working.  Normal motion sensor triggers fine.  Smart detection recordings also show up fine on unifi protect.   Restarting homebridge fixes the problem immediately but unknown when it will start failing again.   
  
**To Reproduce:**

Leave homebridge running for a day.  Observe that the "Person" contact sensor doesn't always trigger.  

**Logs:**

```
[2/23/2022, 3:24:42 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Front steps [UVC G3 Flex]: HomeKit Secure Video has recorded a 19 second motion event.
[2/23/2022, 3:26:20 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Doorbell [UVC G4 Doorbell]: HomeKit Secure Video has recorded a 21 second motion event.
[2/23/2022, 3:26:22 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Front steps [UVC G3 Flex]: HomeKit Secure Video has recorded a 26 second motion event.
[2/23/2022, 3:26:31 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Outside [UVC G4 Pro]: HomeKit Secure Video has recorded a 27 second motion event.
[2/23/2022, 3:26:44 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Front steps [UVC G3 Flex]: HomeKit Secure Video has recorded a 14 second motion event.
[2/23/2022, 3:26:44 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Front steps [UVC G3 Flex]: HomeKit Secure Video event recording ended abnormally: An unexpected protocol failure has occured.
[2/23/2022, 3:26:44 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Outside [UVC G4 Pro]: HomeKit Secure Video has recorded a 10 second motion event.
[2/23/2022, 3:26:44 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Outside [UVC G4 Pro]: HomeKit Secure Video event recording ended abnormally: An unexpected protocol failure has occured.
[2/23/2022, 3:27:20 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Doorbell [UVC G4 Doorbell]: HomeKit Secure Video has recorded a 45 second motion event.
[2/23/2022, 3:27:20 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Outside [UVC G4 Pro]: HomeKit Secure Video has recorded a 32 second motion event.
[2/23/2022, 3:27:20 PM] [homebridge-unifi-protect] Cloudkey [UCK-G2-PLUS] Outside [UVC G4 Pro]: HomeKit Secure Video event recording ended abnormally: An unexpected protocol failure has occured.
```

**Homebridge Configuration:**

```json
{
            "controllers": [
                {
                    "address": "192.168.1.xxx",
                    "mqttUrl": "mqtt://192.168.1.xxx:1883",
                    "password": "hunter2",
                    "username": "hb"
                }
            ],
            "options": [
                "Enable.Motion.SmartDetect",
                "Enable.Motion.SmartDetect.ObjectSensors"
            ],
            "platform": "UniFi Protect",
            "_bridge": {
                "username": "0E:AC:77:8B:64:50",
                "port": 40611
            }
        },
```
        
**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.4.0 
* **Node Version:** v16.13.1
* **Homebridge-UniFi-Protect Plugin Version:** v5.5.0
* **UniFi Protect Version:** 1.21.2
* **UniFi Protect Controller Type:** UCKgen2+ 
* **UniFi Protect Controller Firmware Version:** 2.3.15
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 12 15.1.1
* **Operating System and OS Version:** Docker

**Comment by hjdhjd** [comment] 2022-02-23 23:43
Thanks for the report, but not sure what the issue to address here is: the person contact sensor is unrelated to HKSV. Whether HKSV detects a person or not has little to do with whether or not the person contact sensor is triggered...that comes from what the Protect controller sees and reports. If you can explain in significantly more detail what it is you're trying to do and why you believe this is a bug, I can help...but otherwise, what you've described doesn't sound nor feel like behavior that's necessarily incorrect.

If the **Protect controller** thinks it's seeing a person and the **Person contact sensor** isn't reporting it appropriately, that's an issue. If your issue is that what HKSV reports and what the contact sensor reports don't necessarily agree...that's not a bug, that's the design: they are two different object detection systems that you're trying to use simultaneously and they will not always (or even reliably!) agree on what they're independently detecting.

Thanks!

**Comment by wongchristopher** [comment] 2022-02-23 23:57
Yeah I understand that it has nothing to do with HKSV.  It seems like it was a by product of it being added.    Could you maybe explain in more detail how you get the person detection vs normal motion detections?  The unifi protect app is actually detecting a person (nothing to do with HKSV) but nothing is being triggered in homebridge.    

What I'm using this for is using node-red to unlock the door when it detects a person at the door (with a variable around it to make sure to only trigger if we came home within the last 5 mins).  This was working on the version before HKSV was introduced which leads me to believe that maybe it's blocking the javascript event loop (since it would be streaming video also at that same moment) and maybe not allowing it to trigger?  Only problem with that is that it doesn't entirely make sense either since normal motion detections are working.  

Wanted to get your thoughts before I did a more deep dive to see if I can figure out whats wrong here.  

**Working:**
![Screen Shot 2022-02-23 at 3 52 09 PM](https://user-images.githubusercontent.com/11476101/155430715-1a0b2301-eead-46df-8759-3f83b1d9fc4f.png)

<img width="290" alt="Screen Shot 2022-02-23 at 3 52 20 PM" src="https://user-images.githubusercontent.com/11476101/155430722-03d1f034-c5ba-4983-aeed-6524695e46d7.png">


**Broken:** 
Trigger in Unifi Protect
![Screen Shot 2022-02-23 at 3 51 21 PM](https://user-images.githubusercontent.com/11476101/155430489-8673ac44-3d35-42e0-9e48-b57bb3595202.png)

Event log from Node-Red
<img width="281" alt="Screen Shot 2022-02-23 at 3 54 26 PM" src="https://user-images.githubusercontent.com/11476101/155430635-60c65079-d429-4166-b739-5e1e71b32982.png">

**Comment by hjdhjd** [comment] 2022-02-24 00:00
I gotcha...can we try a few things before we go too far into this...could you disable HKSV in the Home app for the camera in question and see if the behavior all works normally, as you would expect, for the contact sensor? Let's start by isolating the issues and eliminating variables...

How long does the issue typically take to manifest?

Report back and let's take a closer look.

**Comment by wongchristopher** [comment] 2022-02-24 00:09
Ahh okay that sounds like a good idea.  It usually manifest itself within a day.  I don't see any way to disable it on the homebridge side so is it safe to assume you mean on the homekit side?

**Comment by hjdhjd** [comment] 2022-02-24 00:10
Yep...see the remark ***In the Home app*** above...:smile: Set it to streaming instead of recording and streaming. That will disable HKSV. You should also see a log message to that effect in HBUP.

**Comment by wongchristopher** [comment] 2022-02-24 00:16
🤦‍♂️  Thanks! I'll run it for a few days like this to see if it's still flaky!

**Comment by wongchristopher** [comment] 2022-02-28 18:36
Been running it with HKSV turned off on that specific camera only for 4 days now and it's been working exactly like it was before i turned on HKSV.  Looks like turning on HKSV messes with the events.  I've added some additional logging to protect-nvr-events.js to log at line 592 and the weird thing is it looks like it just skips this sometimes when HKSV is turned on.  With HKSV turned off it logs there every time.  

My guess right now is that it's hitting line 518 and skipping the event.  Going to add some logging there and going to try to confirm that guess.   If you look at my working example from before there is almost a 6 seconds difference already.  Would probably be pretty easy to go past  the 10 second limit for stale data.

**Comment by hjdhjd** [comment] 2022-02-28 22:41
I have a sense of what the issue is…it’ll be addressed in an upcoming release. Appreciate the bug report. Closing this one out…I’ll ping you after the next release is out to verify it’s addressed.

Thanks!

**Closed by hjdhjd** 2022-02-28 22:41 UTC

**Comment by wongchristopher** [comment] 2022-02-28 23:19
After doing some logging it looks like it's actually being skipped because of https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/src/protect-nvr-events.ts#L528

Looks like the original motion event doesn't have any detected objects while the skipped ones does.  Hopefully thats in line with what you suspect!
