### ISSUE TITLE
Cameras reset every few days

### ISSUE THREAD

**Issue by Vortec4800** [hjdhjd/homebridge-unifi-protect#116] opened 2020-10-01 01:00 UTC
**Describe The Problem:**

About once a week (it varies) all my cameras in the plug-in reset in HomeKit. Their rooms get changed back to the default, they set themselves as favorites again, and any automations connected to the motion sensors are also lost. It's like HomeKit thinks a new camera is added replacing the old one.

**To Reproduce:**
I haven't been able to pin-point exactly when it happens, as I don't notice immediately. That said I haven't been able to figure out a pattern or identify something that triggers it. It doesn't seem to be related to updating the plug-in or anything like that.

**Logs:**

I don't have any logs because I haven't seen exactly when it happens. I'll upload some if I do find out though.

**Environment:**

* **Homebridge Version:**  1.2.3
* **Node Version:**  12.18.2
* **Homebridge-UniFi-Protect Plugin Version:** 3.7.7
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 11 Pro Max, iOS 14.0.1
* **Operating System and OS Version:**  Official Pi image

**Comment by hjdhjd** [comment] 2020-10-01 01:15
If there’s anything in the logs to indicate what’s going on, feel free to post them.

Was this happening in iOS 13, or only in iOS 14?

Otherwise...there’s really not much to work with here at the moment I’m afraid. But if you get more information or a reproducible use case, please let me know. My guess...assuming you weren’t seeing this in iOS 13, it’s an iOS 14 bug...they tend to have HomeKit errors in the early iOS major releases. I’ve run into a few myself.

**Comment by durosity** [comment] 2020-10-01 08:39
You don't happen to have any older iOS devices connected to your iCloud account do you?  I had this issue a couple of years ago with lots of devices.. it turned out it was because I had an old iPhone still running iOS 9 or 10 or something and it didn't recognise the device type and kept screwing up the database!  Once it was removed the issue cleared itself!

**Comment by Vortec4800** [comment] 2020-10-01 14:02
This did happen on iOS 13 as well as 14, I didn't notice it as much at the time though because I was making so many changes to homebridge setups that it just blended in, but I do remember having to reset the camera settings a few time. I do think it happens more often now though.

Interestingly, I'm having the same issue with a plugin I wrote myself, where the accessory resets once a week or so. I don't have this problem with any of the other plugins I use though, only this one and mine.

I'll let you know if I find anything else out.

**Comment by hjdhjd** [comment] 2020-10-01 14:15
I’ve got 20+ Protect devices...haven’t seen this issue. Not to say I’m the end all and be all of testing here, but that I’ve got a substantial install. 😄 

I haven’t seen this. I don’t think this is a plugin issue. This sounds like a HomeKit or Home app issue.

My instincts tell me that if you’re seeing this, and you’re seeing this across plugins, you could well have a HomeKit corruption problem. I’ve seen that happen (and had it happen to me as well). Can occur if you run betas of iOS etc...as well as general flakiness in earlier versions of HomeKit in larger environments. You might want to explore resetting your entire HomeKit environment (which believe me, sucks) and seeing if that helps. Admittedly an extreme option...but throwing it out there.

This isn’t a plugin issue, I’m confident in that - though feel free to prove me wrong. The plugin has zero control of what rooms you choose to put accessories in. It doesn’t even have knowledge of the concept of a room. 😄

**Comment by hjdhjd** [comment] 2020-10-01 14:20
Let me add one more thing...here’s the only way I can see this issue manifesting itself:

- If you remove the plugin, or the plugin configuration, the accessories will disappear because you’re telling Homebridge to remove these accessories from HomeKit.
- If **homebridge-unifi-protect** removes the accessories, it will definitely log it and tell you it’s doing so. Unless it does, it’s not the one doing the removing unless you outright remove the plugin, or delete the accessory cache in Homebridge.
- **homebridge-unifi-protect** will remove (or add) accessories if it detects a change in your UniFi Protect configuration. Meaning you add or remove a camera. Beta versions of UniFi Protect are known to have weird issues at times with cameras appearing and disappearing, and if you choose to run a beta version of UniFi Protect, you’re on your own because I won’t support beta version of either iOS/tvOS/macOS or UniFi Protect. :smile:

That’s about it. In any of the above events...it’s not a plugin bug, it’s working exactly as intended.

**Comment by Vortec4800** [comment] 2020-10-01 14:28
I'm not running any beta versions of Protect or anything. I'll let you know if I get any more info.

**Comment by hjdhjd** [comment] 2020-10-01 14:29
No logs = no plugin problems. 😄

**Comment by hjdhjd** [comment] 2020-10-01 14:29
I’m going to close this issue out, but please feel free to reopen it if you can get more information. I want you to have the same awesome daily experience many of us do!

**Closed by hjdhjd** 2020-10-01 14:29 UTC
Labels: invalid, not a bug
