### ISSUE TITLE
Smart detections not working with latest version of Protect (4.1.53)

### ISSUE THREAD

**Issue by pbush25** [hjdhjd/homebridge-unifi-protect#1104] opened 2024-08-29 16:54 UTC
### Homebridge UniFi Protect Version

7.1.2

### Homebridge Platform and OS

Raspi 4

### Homebridge Version

1.8.4

### Node Version

18.17.1

### UniFi OS Version

4.0.6

### UniFi Protect Controller Version

4.1.53

### Describe the problem

Prior to updating to Protect 4.1.X, all smart detections from Protect were correctly delivered to HBUP to drive notifications from the cameras, with snapshots, when a person/animal/vehicle was detected. 4.1.X went to GA today, 8/29.

After updating to 4.1.X (since Sunday, 8/25), there has been exactly _one_ smart detection delivered to HBUP. The cameras and their associated contact sensors are still all in Home, and I can still stream the contents of the cameras, so HBUP is communicating with Protect, but the API is presumably not delivering the content correctly for some reason. 

I did try updating my HBUP plugin from 6.8.* to the latest, which did not alleviate the issue. 

### Homebridge HBUP JSON configuration

```json
{
            "controllers": [
                {
                    "address": "192.168.XX.XXX",
                    "doorbellMessages": [
                        {
                            "message": "Coming to the door"
                        }
                    ],
                    "name": "XXXX UNVR",
                    "password": "password",
                    "username": "localadmin"
                }
            ],
            "name": "UniFi Protect",
            "options": [
                "Enable.Motion.SmartDetect",
                "Enable.Motion.SmartDetect.ObjectSensors",
                "Disable.Video.HKSV.D021F9923C27",
                "Disable.Video.HKSV.70A7410C2699",
                "Disable.Video.HKSV.68D79ACF3BD3",
                "Disable.Video.HKSV.68D79AE15DD8",
                "Disable.Video.HKSV.F4E2C67AE608",
                "Disable.Video.HKSV.E063DA00FFD3",
                "Disable.Video.HKSV.F4E2C67AE59E",
                "Enable.Video.Transcode.Hardware.F4E2C67AE608",
                "Enable.Video.Transcode.F4E2C67AE608",
                "Enable.Video.Transcode.Hardware.70A7410C2699",
                "Enable.Video.Transcode.Hardware.68D79ACF3BD3",
                "Enable.Video.Transcode.Hardware.68D79AE15DD8",
                "Enable.Video.Transcode.Hardware.E063DA00FFD3",
                "Enable.Video.Transcode.70A7410C2699",
                "Enable.Video.Transcode.68D79ACF3BD3",
                "Enable.Video.Transcode.D021F9923C27",
                "Enable.Video.Transcode.68D79AE15DD8",
                "Enable.Video.Transcode.E063DA00FFD3",
                "Enable.Log.Motion.70A7410C2699",
                "Enable.Motion.SmartDetect.68D79A3E3F13",
                "Enable.Motion.SmartDetect.ObjectSensors.68D79A3E3F13",
                "Enable.Video.Stream.UseApi.68D79A3E3F13",
                "Enable.Video.Transcode.Hardware.68D79A3E3F13",
                "Disable.Video.Transcode.HighLatency.68D79A3E3F13",
                "Disable.Video.Transcode.68D79A3E3F13",
                "Disable.Video.HKSV.TimeshiftBuffer.68D79A3E3F13"
            ],
            "videoEncoder": "h264_omx",
            "platform": "UniFi Protect"
        },
```

### Relevant log output

```shell
n/a - no logs capturing motion exist since they're not coming from the API.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment] 2024-08-29 17:56
Thanks for the report, but given you’ve been running betas and this GA release is literally hours old, I’m closing this report for now. I appreciate the enthusiasm, but upgrading to beta releases and GAs right when they’re released is a general recipe for disaster.

Thanks for surfacing it…stay tuned.

**Closed by hjdhjd** 2024-08-29 17:56 UTC

**Comment by pbush25** [comment] 2024-08-29 18:18
Closing an actual issue isn't going to help get it resolved. I don't mind running the betas, and have never had this problem before. 

I waited until the release went GA because I know how strict you are with closing issues that aren't in public versions. Your plugin shouldn't be so fragile that upgrading a point release in protect completely breaks it, so much so that you discourage users from using the latest versions.

**Comment by hjdhjd** [comment] 2024-08-29 19:09
While I appreciate feedback, please respect the way I choose to manage issues in my projects.

What you call a point release is often not a point release in the Ubiquiti world. HBUP isn’t fragile, but you’re welcome to your opinion certainly, but the facts and long history of this project would show otherwise.

Whether the issue is open or closed isn’t going to get it on or off my radar any faster. If I’ve closed an issue, I’m aware of it. Again - respect how I choose to manage my projects.

Locking this - I’m not interested in unproductive flame wars. Please be constructive and respectful in the future. Thanks.
