### ISSUE TITLE
Connection instability

### ISSUE THREAD

**Issue by Qonstrukt** [hjdhjd/homebridge-unifi-protect#906] opened 2023-03-30 08:54 UTC
**Describe The Problem:**
Since the latest 6.0.x versions, I've had a quite some connection issues between Homebridge and my UDM-SE.
In the Home app I can open the live view of the Doorbell any time without problems, it's almost instant every time. But the issue is that doorbell notifications aren't arriving, and HKSV events aren't recorded because of it. The logs and MQTT at that point also don't show any doorbell notifications. The Protect app still delivers the notifications on time.

* I've kept configuration fairly minimal.
* Restarting the plug-in in Homebridge solves the issue immediately for a while. 
* Reverting to version 5.4.4 solves the issue immediately.
* Connecting to my UniFi OS Console through the direct URL (https://unifi.qonstrukt.home) is quick and responsive.

My setup is running Homebridge on a beefy x86_64 server, which is connected via cables to the same network as the UDM-SE, which serves as the main gateway/router for my network.

The UDM-SE is serving only the Doorbell G4.

**Logs**

```
[3/29/2023, 5:55:26 PM] [homebridge-unifi-protect] Dream Machine SE [UDM-PRO-SE]: API error: Protect controller is taking too long to respond to a request. This error can usually be safely ignored.
[3/29/2023, 5:55:26 PM] [homebridge-unifi-protect] Dream Machine SE [UDM-PRO-SE]: API error: Original request was: https://unifi.qonstrukt.home/proxy/protect/api/bootstrap
[3/29/2023, 5:55:26 PM] [homebridge-unifi-protect] unifi.qonstrukt.home: API error: Unable to retrieve the UniFi Protect controller configuration. Retrying.
[3/29/2023, 5:55:30 PM] [homebridge-unifi-protect] unifi.qonstrukt.home: API error: Protect controller is taking too long to respond to a request. This error can usually be safely ignored.
[3/29/2023, 5:55:30 PM] [homebridge-unifi-protect] unifi.qonstrukt.home: API error: Original request was: https://unifi.qonstrukt.home/api/auth/login
```

**Homebridge Configuration:**

```json
        {
            "controllers": [
                {
                    "address": "unifi.qonstrukt.home",
                    "defaultDoorbellMessage": "WELKOM!",
                    "mqttTopic": "unifi/protect",
                    "mqttUrl": "mqtt://mqtt.qonstrukt.home",
                    "password": "<redacted>",
                    "username": "homebridge"
                }
            ],
            "options": [
                "Disable.Video.Transcode.HighLatency"
            ],
            "_bridge": {
                "username": "<redacted>",
                "port": "<redacted>"
            },
            "platform": "UniFi Protect"
        }
```

**Environment:**

* **Homebridge Version:** v1.6.0
* **Node Version:** v18.13.0
* **Homebridge-UniFi-Protect Plugin Version:** v6.0.3
* **UniFi Protect Version:** v2.7.34
* **UniFi Protect Controller Type:** UDM-SE
* **UniFi Protect Controller Firmware Version:** UniFi OS 3.0.18
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** All devices imaginable in the Apple ecosystem, running 16.3.2 or 16.4
* **Operating System and OS Version:** Docker with a bridged network on TrueNAS Scale

**Comment by hjdhjd** [comment] 2023-03-30 19:06
First, thanks for running on one of my favorite configurations - big TrueNAS fan. 😄 

Second...how strong's the WiFi connection for the G4 Doorbell? I presume it's not the Pro as well, BTW.

Third...are there specific log messages relating to any HKSV activities? Do they ALL fail? Some? Trying to get a sense of the magnitude of the issue you're experiencing.

I have my suspicions here, but it's edge cases like these that I'm most keen to test to ensure I get it right in 6.x.

**Comment by Qonstrukt** [comment] 2023-03-30 21:15
Yeah it's a great setup, very fast and reliable NAS software, I love it. 😊

The WiFi connection is "Good" as Protect classifies it, "Excellent" as Network classifies it. About a 300mbps rate to the UniFi 6 Lite 2 meters away from it. 

There are no HKSV related failures in the logs, and notifications only start to fail after those 5 log lines I listed. Before that everything is fine. It's been running fine again for almost 12 hours mow, but I expect it to fail again early tomorrow. 
Then I'll restart the plug-in and everything works again. 

In the previous version, if I would upgrade Protect for example, I would get messages of the HKSV web socket being disconnected which made it always clear to me that notifications are broken from that point on. So after every Protect upgrade I already would restart your plug-in. But it would be stable for days or even weeks other than that.

**Comment by hjdhjd** [comment] 2023-03-31 01:58
Is the only camera you have in your setup the Doorbell, and if not, do the issues exist elsewhere?

I’m trying to replicate and narrow down a specific use case I can troubleshoot.

Can you also humor me and try something: delete the local user account you created on the UDM and recreate it.

Let’s see if that helps.

You should definitely never need to restart HBUP to get things going…it should gracefully recover from issues and if it doesn’t…well, I want to know so I can ensure this remains a very maintenance-free experience. 😄

**Comment by Qonstrukt** [comment] 2023-04-03 14:16
Sorry, was out for a couple of days. 😉  

I'll give it a go with your new release, but in the meantime I've been running v5.4.4 again, which exhibits none of the issues I had. My doorbell is stil sending Homekit notifications properly, and Activity notifications have been much more reliable as well after having installed v5.4.4 on Friday.

I'm running a G4 Doorbell currently as a single device. I can give the new local user a try if v6.2.1 is still acting problematic.

**Comment by hjdhjd** [comment] 2023-04-03 19:58
No worries. Give it a go...nothing material changed that should impact this issue in the ensuing releases, but I'm deeply interested in seeing if the issue is still present in 6.2.1. If it is, I'd like to work with you more on troubleshooting it...you've got a very clean/simple use case and to the extent there's an issue in HBUP, I want to get it addressed.

Also...try recreating the user account. It's a real fix in quite a few network-related cases I've come across. The v3 UniFiOS upgrade isn't always clean and local user accounts tends to be a little-tested edge case. Recreating the user seems to fix whatever the issue is.

We'll get it tracked down one way or the other - thanks again.

**Comment by VincentWallet** [comment] 2023-04-03 21:23
Hello,

Sorry and thanks for your fast reply !.

I tried both solution : new fresh user in unifi protect and your new
version 6.2.2 but still no motion event (but yes in my test, i saw this
afternoon that sometimes, the unifi console MAC adress was used instead of
the MAC from cameras ) :

I just retrieve some snapshot but don't know why they trigger the snapshot.
Maybe the missing motion event trigger is doing it  ?




[image: image.png]

Regards,

**Comment by hjdhjd** [comment] 2023-04-04 13:53
I'm still betting on that this is a v3 UniFiOS local user issue. Delete and recreate the user on the UDM. Let me know, thanks!

**Comment by hjdhjd** [comment] 2023-04-04 21:24
@VincentWallet 

Please do not hijack another person's support thread. It's poor practice and not the way I choose to provide support. If you want support, please open an issue and completely fill out the issue template. Thanks. Deleting the comment.

**Comment by VincentWallet** [comment] 2023-04-04 21:32
Unless i'm mistaken or i didn't know something : i did not respond to
another person's support thread and i would understand your point of view
about providing support.

For info, I already opened the issue 910 that you have already closed :
https://github.com/hjdhjd/homebridge-unifi-protect/issues/910 by suggesting
that it will be fixed in 6.2.2.

Sorry again if i missed something but i think not ?

Regards,

**Comment by hjdhjd** [comment] 2023-04-04 21:53
You are responding in someone else's issue @VincentWallet - please cease and respond in your own issue. If you don't know how to do that, please read through the Github help pages. Thanks.

**Comment by hjdhjd** [comment] 2023-04-05 17:39
@Qonstrukt Give v6.2.5 a go as well...

**Comment by Silverstrale** [comment] 2023-04-06 18:46
I think I experience the same problem with missing notifications as the issue creator and I am writing this comment to hopefully improve the possibility to find the problem.
The difference in my case is that I do not have a unifi door bell, but do not get any notifications for detections from cameras (I have 5) when using homebridge-unifi-protect version 6.2.8 (and some of the earlier version 6.x.x but I do not remember which). Reverting back to version 5.5,4 enables the notifications again.

**Comment by hjdhjd** [comment] 2023-04-06 22:56
@Silverstrale Thanks for the note and the additional data point...please open a separate issue if you'd like support. Things that look similar sometimes are, and sometimes are not correlated. Thanks again.

**Comment by hjdhjd** [comment] 2023-04-08 21:53
v6.3.0 should solve this issue - I tracked it down I believe. Thanks again for the report @Qonstrukt - verify it's working correctly and we can close this out.

**Comment by Qonstrukt** [comment] 2023-04-09 12:49
Sorry about the silence, but I've been upgrading with all your new releases throughout the week. And mainly since 6.2.8 all problems seem to have vanished!

I've just upgraded to 6.3.0 as you recommended, and I wil keep you posted in new issues if new problems arise. But LGTM so far! Thanks for all the effort! 😊

**Comment by hjdhjd** [comment] 2023-04-10 00:27
Glad to hear it. Closing this one out.

**Closed by hjdhjd** 2023-04-10 00:27 UTC
