### ISSUE TITLE
Streaming broken after Homebridge v.1.4.1 update

### ISSUE THREAD

**Issue by joshuamallow** [hjdhjd/homebridge-unifi-protect#740] opened 2022-05-22 12:39 UTC
**Describe The Problem:**
Can no longer open a live stream of the UniFi cameras within HomeKit.

**To Reproduce:**
Open HomeKit on iPhone or iPad, click on video to load live stream. Video stays loading and never displays. Worked fine before Homebridge 1.4.1 update.

**Logs:**

```
[5/22/2022, 7:31:07 AM] [homebridge-unifi-protect] Security Cameras [UNVR4] Doorbell [UVC G4 Doorbell]: Streaming request from 192.168.1.216: 1280x720@30fps, 299 kbps. Using 1600x1200@30fps (High), 6000 kbps.
[5/22/2022, 7:31:43 AM] [homebridge-unifi-protect] Security Cameras [UNVR4] Doorbell [UVC G4 Doorbell]: Stopped video streaming session.
```

**Homebridge Configuration:**

```json

```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.4.1
* **Node Version:** 16.14.2
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.0
* **UniFi Protect Version:**1.21.6
* **UniFi Protect Controller Type:** UNVR
* **UniFi Protect Controller Firmware Version:** UNVR 2.4.8
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iOS 15.5 / iPad OS 15.5
* **Operating System and OS Version:** Homebridge running on Synology NAS with intel CPU

**Comment by gramster1** [comment] 2022-05-25 02:09
Also having the same issue with these logs reported:

FFmpeg process ended unexpectedly with an exit code of 1.

FFmpeg command line that errored out was: ffmpeg -hide_banner -probesize 2048 -max_delay 500000 -r 24 -rtsp_transport tcp -i rtsps://10.0.0.10:7441/OhR82AgV6suVC9IK?enableSrtp -map 0:v -vcodec copy -payload_type 99 -ssrc 10861519 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params XBBtxcnqfjXetnZs6DeagnYQR7lsLfDPTF+iaqfx srtp://10.0.0.212:61031?rtcpport=61031&localrtcpport=61031&pkt_size=564 -map 0:a -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 48k -ac 1 -payload_type 110 -ssrc 8211300 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ThOXfFCb0i2VyFD13Ohp6DwvkGzVUOtHhqv6ztT1 srtp://10.0.0.212:58728?rtcpport=58728&localrtcpport=58728&pkt_size=188

Stream #2: not enough frames to estimate rate; consider increasing probesize

**Comment by hjdhjd** [comment] 2022-05-25 02:12
@gramster1 please open a separate issue if you have a problem to report, or feel free to use the Discord. One person, one issue. Thanks.

**Comment by hjdhjd** [comment] 2022-05-25 02:13
@joshuamallow I’m not seeing this behavior…confirm the issue by reverting to 1.4.0 or the last working Homebridge. Thanks!

**Comment by gramster1** [comment] 2022-05-25 02:15
> @joshuamallow I’m not seeing this behavior…confirm the issue by reverting to 1.4.0 or the last working Homebridge. Thanks!

what was the last version without issues? I have downgraded all the way to 1.3.7 and the issue remains.

**Comment by gramster1** [comment] 2022-05-25 02:31
@joshuamallow I've tried downgrading homebridge, the UniFi protect plugin, and homebrigde UI to older versions, the issue is persisting.

**Comment by joshuamallow** [comment] 2022-05-25 02:50
The streams are working somewhat. For example, a doorbell ring will send a HomeKit notification about 2-3 minutes afterwards. So HomeKit is seeing the video still, albeit delayed. Live streaming will work on occasion but it’s rare. Downgrading Homebridge to 1.4.0 doesn’t seem to fix it. Thought the problem occurred right after upgrading to 1.4.1. There was also a UniFi update, not sure when it went live but I updated the same time as Homebridge.

**Comment by gramster1** [comment] 2022-05-25 02:52
gotcha, my streams are completely broken, happened at the same time as well. Snapshots are still working however.

**Comment by hjdhjd** [comment] 2022-05-25 03:01
@joshuamallow Doorbell rings being delayed are not a Homebridge or HBUP issue, it’s a HomeKit issue, especially when upgrading iOS/tvOS versions. Well documented elsewhere - reboot all your HomeKit hubs and that should help a bit.

I suspect the issue is likely related to your Protect update. There’s a major update I’ll be pushing in the next few days that should help as well.

In the meantime - closing this issue given the issue isn’t Homebridge version related…feel free to reach out on the Discord.

**Closed by hjdhjd** 2022-05-25 03:01 UTC
