### ISSUE TITLE
Not Seeing HKSV TImeline In Home App Even After Setting Recording Options To Stream & Record

### ISSUE THREAD

**Issue by Wildcat1** [hjdhjd/homebridge-unifi-protect#695] opened 2022-03-07 20:01 UTC
**Describe The Problem:**
Hi there, just upgraded to 5.5.0 and see the Recording Options for the camera (G4 Doorbell) BUT I am not seeing any HKSV timeline in the Home App for the camera even when I do test movement in front of it. It seemed to work for a second but now all I see it the Live button and that's it. To confirm I assume Limited Admin role with View only access to the Unifi Protect app is good as I've tried it with this and Administrator access to the app and still no change ?

**To Reproduce:**
Upgraded to V5.5.0, went into Home App, set Recording Options for G4 Doobrell to Stream & Record. Tested Motion events and no timeline is seen in the Home App. Worked briefly but then no timeline from then on, nothing else changed in the environment

**Logs:**
Not sure which part of the log you need, please advise

```
Show the Homebridge logs here.
Not sure which part is needed as there are no errors showing on the Status / Logs
```

**Homebridge Configuration:**

```json
"motionDuration": 10,
            "platform": "UniFi Protect"
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.4.0
* **Node Version:** 16.14.0
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 1.21.3
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** If you mean version on the UDMP its 1.11.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iPhone 12 Pro Max + Apple TV 4K running 15.4
* **Operating System and OS Version:** macOS 10.15.7

**Comment by Wildcat1** [comment] 2022-03-07 20:32
Also, just a few quick updates 1) have tried this on ANY motion + specific motion (people etc) and same results, LIVE button is available but no HKSV timeline. 2) When I change Stream/Record options I DO get the notification from Home that those were changed for the camera so it does see the changes BUT still no timeline, 3) no notifications popup showing motion detected etc even though enabled 4) added Administrator + View (was originally only View) to the Limited Admin role for Unifi Protect on the controller BUT still no difference

**Comment by hjdhjd** [comment] 2022-03-07 20:39
The plugin is working fine - not a bug I'm afraid. - if HBUP  tells you it's recording, it's doing exactly what HomeKit is asked it to do and is functioning properly. 

You might want to try disabling recording in the Home app (i.e. set to stream only), then rebooting all of your HomeKit hubs (Apple TVs, HomePods, etc.), and then re-enabling recording and seeing if that works.

Also: messing around with "limited" admin privs for HBUP is inadvisable - just bite the bullet and give it all the privileges it wants until you're up and running, and then tweak if you must. People get a little overly zealous with this stuff. :smile:

Best of luck.

**Comment by hjdhjd** [comment] 2022-03-07 20:46
I should add as a reminder - you also seem to be running a beta iOS release - all beta releases of iOS/tvOS/iPadOS/macOS and Ubiquiti are unsupported.

**Comment by Wildcat1** [comment] 2022-03-07 20:52
Couple of follow ups:
1 - When you say if 'HBUP tells you it's recording' where do I see that to confirm ?
2 - I had Limited Admin setup before with only VIEW access on the Unifi App, my question is do I need more than VIEW access ? The only reason I added Admin to the Unifi App was because this stopped working (HKSV timeline)
3 - I'll definitely reboot all HomeKit Hubs and see if that works
4 - Yes I'm running beta but have also tried release version and see the same. As I mentioned, on beta it was still working for a little while then stopped and now just shows LIVE even though Recording Options is present which shows me it DOES detect this as an HKSV compatible camera. Therefore not sure how to pin point what if anything changed because nothing in the infrastructure has been updated except the plugin and signing up for the 2TB plan. 

Thanks for any further assistance in trying to fault isolate this issue

**Comment by hjdhjd** [comment] 2022-03-07 21:18
Check the Homebridge logs...you should see something like:

`HomeKit Secure Video event recording enabled: 3840x2160@24fps (High), 2000 kbps with a 4 second timeshift buffer.`

What that means is that HomeKit Secure Video is configured correctly in the plugin, and your issue isn't here. I'd also encourage you to take the time to read the HKSV-related documentation for the plugin which explains how HKSV actually works.

**Beyond that, you're on your own I'm afraid...I won't provide any support for any beta OS versions. It's explicitly out of scope for this plugin - that means no beta OSs at all involved in anything related to HomeKit in the apple ecosystem - there are side effects that can occur when running beta operating systems that span far beyond those devices (impacting iCloud, HomeKit, and other capabilities).**

**Closed** 2022-03-09 13:56 UTC
Labels: invalid, not a bug
