### ISSUE TITLE
Starting Homebridge fires a doorbell ring and motion notification

### ISSUE THREAD

**Issue by ianiv** [hjdhjd/homebridge-unifi-protect#161] opened 2020-11-03 05:23 UTC
**Describe The Problem:**
I installed version 4.0.0 today and noticed that whenever Homebridge starts, I immediately receive a HomeKit notification for both ring and motion for my doorbell

**To Reproduce:**
- Use a G4 doorbell
- Enable HomeKit motion and doorbell notifications for the doorbell
- Start up (or restart) Homebridge

**Logs:**

```
[11/2/2020, 9:13:41 PM] Homebridge v1.2.3 is running on port 51826.
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS]: Connected to the Protect controller API (address: *** mac: ***).
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS]: The user 'homebridge' requires the Administrator role in order to automatically configure camera RTSP streams.
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: **** [UVC G3 Flex] (address: **** mac: ****).
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: Doorbell [UVC G4 Doorbell] (address: **** mac: ****).
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: **** [UVC G3 Micro] (address: **** mac: ****).
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: **** [UVC G3 Flex] (address: **** mac: ****).
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: **** [UVC G3 Micro] (address: **** mac: ****).
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: **** [UVC G3 Flex] (address: **** mac: ****).
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: **** [UVC G3 Flex] (address: **** mac: ****).
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS]: Controller refresh interval set to 5 seconds.
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS] Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: LEAVE PACKAGE AT DOOR.
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS] Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: DO NOT DISTURB.
[11/2/2020, 9:13:42 PM] [UniFi Protect] Home [UCK-G2-PLUS] Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: COME TO THE BACK.
[11/2/2020, 9:13:47 PM] [UniFi Protect] Home [UCK-G2-PLUS]: A doorbell has been detected. Setting the controller refresh interval to 2 seconds.
```

**Homebridge Configuration:**

```json
        {
            "controllers": [
                {
                    "address": "***",
                    "password": "***",
                    "username": "***"
                }
            ],
            "options": [
                "Enable.MotionTrigger"
            ],
            "motionDuration": 5,
            "platform": "UniFi Protect"
        }
```

**Screenshots:**
n/a

**Environment:**

* **Homebridge Version:** 1.2.3
* **Node Version:** v14.5.0
* **Homebridge-UniFi-Protect Plugin Version:** 4.0.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 11 Pro, iOS 14.1
* **Operating System and OS Version:** macOS 10.15.7

**Comment by hjdhjd** [comment] 2020-11-03 13:10
Hi there - thanks for the report. Can you do a few things:

* Homebridge v1.2.3 is a withdrawn version - Homebridge v1.1.6 is the most recent production release. Please install it instead. There are known issues with v1.2.x, especially in Ubiquiti-based environments. The easiest way to revert is to uninstall Homebridge and reinstall it via npm.
* Enable logging of motion and ring events - `Enable.Log.Motion` and `Enable.Log.Doorbell`.

What version of the UniFi Protect controller are you running?

Also - your existing feature option for motion trigger is incorrect as of 4.0. Please review the feature option documentation as most feature options have been renamed in 4.x.

If you're able to still recreate the issue once you've done the above, please post the logs showing the doorbell and motion events. I've been unable to reproduce this on my end with a similar setup.

**Comment by skb3735** [comment] 2020-11-03 14:12
I have the same issue. Random doorbell rings and motion detection

**Comment by hjdhjd** [comment] 2020-11-03 15:23
@skb3735 Thanks for the report. Please provide all of the above information if you’d like to troubleshoot this.

**Comment by ianiv** [comment] 2020-11-03 17:26
Had no idea the 1.2 versions where withdrawn! I have downgraded to 1.1.6 by uninstalling and reinstalling as you suggested.
I am using Protect 1.13.7 on a Cloud Key G2+

My config now looks like this

```
{
            "controllers": [
                {
                    "address": "***",
                    "password": "***",
                    "username": "***"
                }
            ],
            "options": [
                "Enable.Log.Doorbell",
                "Enable.Log.Motion"
            ],
            "motionDuration": 5,
            "platform": "UniFi Protect"
        }
```

When I restart, the log look like this. Every camera generates a motion event (and ring for the doorbell) at the same time. I can guarantee there was no motion for at least 3 of the cameras, and definitely nobody ringing the doorbell.

```
[11/3/2020, 9:16:25 AM] Homebridge is running on port 51826.
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS]: Connected to the Protect controller API 
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS]: The user 'homebridge' requires the Administrator role in order to automatically configure camera RTSP streams.
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: *** [UVC G3 Flex]
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: Doorbell [UVC G4 Doorbell]
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: *** [UVC G3 Micro]
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: *** [UVC G3 Flex]
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: *** [UVC G3 Micro]
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: *** [UVC G3 Flex]
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS]: Discovered camera: *** [UVC G3 Flex] 
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS]: Controller refresh interval set to 5 seconds.
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS] Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: LEAVE PACKAGE AT DOOR.
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS] Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: DO NOT DISTURB.
[11/3/2020, 9:16:30 AM] [UniFi Protect] Home [UCK-G2-PLUS] Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: COME TO THE BACK.
[11/3/2020, 9:16:36 AM] [UniFi Protect] Home [UCK-G2-PLUS]: A doorbell has been detected. Setting the controller refresh interval to 2 seconds.
[11/3/2020, 9:16:36 AM] [UniFi Protect] Home [UCK-G2-PLUS] *** [UVC G3 Flex]: Motion detected.
[11/3/2020, 9:16:36 AM] [UniFi Protect] Home [UCK-G2-PLUS] Doorbell [UVC G4 Doorbell]: Motion detected.
[11/3/2020, 9:16:36 AM] [UniFi Protect] Home [UCK-G2-PLUS] Doorbell [UVC G4 Doorbell]: Doorbell ring detected.
[11/3/2020, 9:16:36 AM] [UniFi Protect] Home [UCK-G2-PLUS] *** [UVC G3 Micro]: Motion detected.
[11/3/2020, 9:16:36 AM] [UniFi Protect] Home [UCK-G2-PLUS] *** [UVC G3 Flex]: Motion detected.
[11/3/2020, 9:16:36 AM] [UniFi Protect] Home [UCK-G2-PLUS] *** [UVC G3 Micro]: Motion detected.
[11/3/2020, 9:16:36 AM] [UniFi Protect] Home [UCK-G2-PLUS] *** [UVC G3 Flex]: Motion detected.
[11/3/2020, 9:16:36 AM] [UniFi Protect] Home [UCK-G2-PLUS] *** [UVC G3 Flex]: Motion detected.
```

Let me know what else I can do to help debug this.

**Comment by hjdhjd** [comment] 2020-11-03 17:46
Ah. UCK...grumble. Let me take a closer look. :smile:

One more thing...if you go to the UniFi Protect webUI and go to the events tab...see if the events correlate against what you’re seeing (or not seeing) in the Homebridge logs.

UCK is a big clue...I’ll take a closer look later today. If you can gather a little more of the above info, I’d appreciate it.

Thanks!

**Comment by ianiv** [comment] 2020-11-03 18:05
There is no correlation between the log above and the events in the Protect webUI

**Comment by hjdhjd** [comment] 2020-11-03 18:52
Thanks @ianiv - one last thing...verify that downgrading to v3.7.9 fixes your issues. 😄 

Appreciate you taking the time and effort to help track this down.

**Comment by ianiv** [comment] 2020-11-03 19:22
Downgrading to v3.7.9 fixes the issue.
And thank YOU for making this awesome plugin.

**Comment by hjdhjd** [comment] 2020-11-03 19:32
@ianiv One more thing...is this issue specific to the G4 Doorbell, or do you see the issue on other camera types?

**Comment by ianiv** [comment] 2020-11-03 19:41
All the cameras I have. I wasn't receiving notifications because I have them off for those in the Home app, but you can see the events being logged for all the cameras at the same time.

**Comment by hjdhjd** [comment] 2020-11-04 01:55
@ianiv Thanks for being so thorough in your information. I've recreated the issue and it's fixed in v4.0.1. Try it out and let me know. Thanks!

**Comment by ianiv** [comment] 2020-11-04 21:18
@hjdhjd v4.0.1 looks good!

**Comment by hjdhjd** [comment] 2020-11-04 21:53
Thanks for the report. Closing this one.

**Closed by hjdhjd** 2020-11-04 21:53 UTC
