### ISSUE TITLE
Doorbell Trigger

### ISSUE THREAD

**Issue by SerrII** [hjdhjd/homebridge-unifi-protect#318] opened 2021-03-03 17:51 UTC
**Describe The Problem:**
I set up the doorbell trigger so that I can create a scene as soon as someone rings the doorbell. Unfortunately, this trigger doesn't always work, which is a shame. I hope the problem can be resolved quickly.

**Homebridge Configuration:**

```json
{
            "controllers": [
                {
                    "address": "192.168.1.1",
                    "password": "&6-GH99)!Maxi2001",
                    "username": "dirk.cleven@me.com"
                }
            ],
            "options": [
                "Enable.Doorbell.Trigger"
            ],
            "platform": "UniFi Protect"
        }
```

**Environment:**

* **Homebridge Version: v1.3.1**
* **Node Version: v14.15.1** 
* **Homebridge-UniFi-Protect Plugin Version: v4.3.5**
* **UniFi Protect Version: 1.17.4**
* **UniFi Protect Controller Type: UDMPRO**
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:iPhone 12, iMac Air M1**
* **Operating System and OS Version:Ubuntu**

**Comment by hjdhjd** [comment] 2021-03-03 17:53
Duplicate of a known issue with 1.17 onward. It will be fixed in an upcoming release.

**Closed by hjdhjd** 2021-03-03 17:53 UTC
