### ISSUE TITLE
Unable to login into controller from homebridge error

### ISSUE THREAD

**Issue by ianknight77** [hjdhjd/homebridge-unifi-protect#1015] opened 2023-11-03 14:34 UTC
**Describe The Problem:**
Following error is presented when trying to configure. Unable to login to the UniFi Protect controller. Please check your controller address, username, and password.

**To Reproduce:**
After initial install, trying to configure the plugin.

**Logs:**
Homebridge logs

```
[03/11/2023, 14:48:31] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge D4CD) is running on port 51102.
[03/11/2023, 14:48:32] [AC Upstairs] Launched child bridge with PID 3576
[03/11/2023, 14:48:32] [UniFi Protect] Launched child bridge with PID 3568
[03/11/2023, 14:48:32] Registering accessory 'homebridge-daikin-local.Daikin-Local'
[03/11/2023, 14:48:32] [AC Upstairs] Loaded homebridge-daikin-local v1.1.0 child bridge successfully
[03/11/2023, 14:48:32] [AC Upstairs] Display Units:  Celsius
[03/11/2023, 14:48:32] [AC Upstairs] *****************************************************************
[03/11/2023, 14:48:32] [AC Upstairs]   homebridge-daikin-local version 1.1.0
[03/11/2023, 14:48:32] [AC Upstairs]   GitHub: https://github.com/cbrandlehner/homebridge-daikin-local 
[03/11/2023, 14:48:32] [AC Upstairs] *****************************************************************
[03/11/2023, 14:48:32] [AC Upstairs] accessory name: AC Upstairs
[03/11/2023, 14:48:32] [AC Upstairs] accessory ip: 192.168.1.109
[03/11/2023, 14:48:33] Homebridge v1.6.1 (HAP v0.11.1) (AC Upstairs) is running on port 40515.
[03/11/2023, 14:48:33] [AC Upstairs] Your Daikin WIFI controller model: FCAHG100HVEB
[03/11/2023, 14:48:33] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[03/11/2023, 14:48:33] [UniFi Protect] Loaded homebridge-unifi-protect v6.15.1 child bridge successfully
[03/11/2023, 14:48:33] [UniFi Protect] No host or IP address has been configured.
[03/11/2023, 14:48:33] Homebridge v1.6.1 (HAP v0.11.1) (UniFi Protect) is running on port 31824.
[03/11/2023, 14:48:33] [UniFi Protect] Using FFmpeg version: 6.0-homebridge-alpine-aarch64-static.
[03/11/2023, 14:48:33] [AC Upstairs] The firmware version is 4_0_3
[03/11/2023, 14:57:50] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
[03/11/2023, 14:57:51] [Homebridge UI] [homebridge-unifi-protect] (node:4169) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
[03/11/2023, 14:57:51] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getErrorMessage
[03/11/2023, 15:01:06] [Homebridge UI] [homebridge-unifi-protect] Terminating child process...
[03/11/2023, 15:01:06] [Homebridge UI] [homebridge-unifi-protect] Child process ended
[03/11/2023, 15:23:39] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
[03/11/2023, 15:23:39] [Homebridge UI] [homebridge-unifi-protect] (node:4712) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
[03/11/2023, 15:23:40] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getErrorMessage
[03/11/2023, 15:24:00] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
[03/11/2023, 15:24:00] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getErrorMessage
[03/11/2023, 15:24:03] [Homebridge UI] [homebridge-unifi-protect] Terminating child process...
[03/11/2023, 15:24:03] [Homebridge UI] [homebridge-unifi-protect] Child process ended
[03/11/2023, 15:28:30] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
[03/11/2023, 15:28:30] [Homebridge UI] [homebridge-unifi-protect] (node:4817) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
[03/11/2023, 15:28:30] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getErrorMessage
```

**Homebridge Configuration:**

```json
{
    "controllers": [
        {}
    ],
    "name": "UniFi Protect",
    "platform": "UniFi Protect",
    "_bridge": {
        "username": "0E:1E:B4:E8:CB:25",
        "port": 31824
    }
}
```

**Screenshots:**
![image](https://github.com/hjdhjd/homebridge-unifi-protect/assets/149727034/abde8333-6f0f-4eb3-b04e-a4c12b406f09)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.18.2
* **Homebridge-UniFi-Protect Plugin Version:** 6.15.1
* **UniFi Protect Version:** 2.8.35 or 2.9.33
* **UniFi Protect Controller Type:** Dream Router
* **UniFi Protect Controller Firmware Version:** 2.8.35
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iOS 17
* **Operating System and OS Version:** Raspian 64 bit 2023-10-10

**Comment by ianknight77** [comment] 2023-11-03 14:35
Checked multiple users account and mulitple admin settings. Reinstalled Unifi Protect application. Reinstalled homebridge.

**Comment by kevalkdesai** [comment] 2023-11-03 15:19
Can everyone please stop submitting reports for this? JFC

**Comment by sil1902** [comment] 2023-11-03 18:09
The Problem is that the plugin causes "You've reached the login attempt limit. Please wait a few minutes before trying again." I cannot login with the local account via web-browser. I get this message when I try to log in.

**Comment by hjdhjd** [comment] 2023-11-05 03:21
> The Problem is that the plugin causes "You've reached the login attempt limit. Please wait a few minutes before trying again." I cannot login with the local account via web-browser. I get this message when I try to log in.
> 
> There seams to be a limit, that you can change in the UDM. https://community.ui.com/questions/Unifi-API-Rate-Limited/ba82a718-9418-46b0-8f2f-235bfc647f9b
> 
> This limit is by default http rate limit (Limit 20 requests per second) http.limit.second = 1 http.limit.count = 20 success login rate limit (limit 5 request pre minute) success.login.limit.count = 5
> 
> I change my settings to the following http rate limit (Limit 20 requests per second) http.limit.second = 1 http.limit.count = 200 success login rate limit (limit 5 request pre minute) success.login.limit.count = 50
> 
> Reboot my UDM SE and my Homebridge and so far it looks good. I am not sure but in the threat there is someone talking about cached credentials. [...] Ideally the client software would cache the authentication data and not need to sign in for every single request. I’m sure this can be done with the api client underlying the software you use. [...]
> 
> Maybe that is somehow a hint to look for this and add it into the plug in. I am not really a programming guy so I can't help out here.

**None of this is true when it comes to this plugin.** HBUP does not continuously login to the Protect API. We login once. A cursory glance at the UniFi OS log on any Protect controller would show you this.

Closing this thread - I've addressed these issues elsewhere.

**Closed by hjdhjd** 2023-11-05 03:21 UTC
